# Generated by Django 2.2 on 2020-09-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='priice',
            new_name='price',
        ),
    ]
