# Generated by Django 2.2 on 2020-09-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200924_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Shirt', 'Shirt'), ('Tshirt', 'Tshirt'), ('Cap', 'Cap')], max_length=2),
        ),
    ]
