# Generated by Django 2.2 on 2020-09-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200924_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Shirt', 'Shirt'), ('Tshirt', 'Tshirt'), ('Cap', 'Cap')], max_length=10),
        ),
    ]
