# Generated by Django 2.2 on 2020-09-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200925_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderd',
            new_name='ordered',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='orderd',
            new_name='ordered',
        ),
    ]
